const VOCABULARY_LEVELS = {
    1: { name: '入门', description: '小学3-4年级 / CEFR A1', wordCount: 300, cefr: 'A1', schoolLevel: '小学3-4年级' },
    2: { name: '基础', description: '小学5-6年级 / CEFR A1-A2', wordCount: 300, cefr: 'A2', schoolLevel: '小学5-6年级' },
    3: { name: '进阶', description: '初中1-2年级 / CEFR A2-B1', wordCount: 400, cefr: 'B1', schoolLevel: '初中1-2年级' },
    4: { name: '高级', description: '初中3-高中1年级 / CEFR B1-B2', wordCount: 400, cefr: 'B2', schoolLevel: '初中3-高中1年级' },
    5: { name: '精通', description: '高中及以上 / CEFR B2-C1', wordCount: 500, cefr: 'C1', schoolLevel: '高中及以上' },
    6: { name: '专家', description: '大学英语四级 / CEFR C1-C2', wordCount: 500, cefr: 'C2', schoolLevel: '大学英语四级' },
    7: { name: '大师', description: '大学英语六级及以上 / CEFR C2+', wordCount: 600, cefr: 'C2+', schoolLevel: '大学英语六级及以上' },
    8: { name: '至尊', description: '专业八级/雅思7.5+ / CEFR C2++', wordCount: 500, cefr: 'C2++', schoolLevel: '专业八级/雅思7.5+' }
};

const VOCABULARY_BY_LEVEL = {
    1: [
        { word: 'a', phonetic: '/ə/', meaning: '一个', example: 'I have a book.' },
        { word: 'an', phonetic: '/æn/', meaning: '一个', example: 'This is an apple.' },
        { word: 'the', phonetic: '/ðə/', meaning: '这个', example: 'The cat is black.' },
        { word: 'I', phonetic: '/aɪ/', meaning: '我', example: 'I am happy.' },
        { word: 'you', phonetic: '/juː/', meaning: '你', example: 'You are my friend.' },
        { word: 'he', phonetic: '/hiː/', meaning: '他', example: 'He likes apples.' },
        { word: 'she', phonetic: '/ʃiː/', meaning: '她', example: 'She is beautiful.' },
        { word: 'it', phonetic: '/ɪt/', meaning: '它', example: 'It is a dog.' },
        { word: 'is', phonetic: '/ɪz/', meaning: '是', example: 'This is a pen.' },
        { word: 'are', phonetic: '/ɑːr/', meaning: '是', example: 'You are tall.' },
        { word: 'have', phonetic: '/hæv/', meaning: '有', example: 'I have a book.' },
        { word: 'go', phonetic: '/ɡəʊ/', meaning: '去', example: 'I go to school.' },
        { word: 'come', phonetic: '/kʌm/', meaning: '来', example: 'Come here.' },
        { word: 'see', phonetic: '/siː/', meaning: '看', example: 'I see a bird.' },
        { word: 'say', phonetic: '/seɪ/', meaning: '说', example: 'Say hello.' },
        { word: 'eat', phonetic: '/iːt/', meaning: '吃', example: 'I eat breakfast.' },
        { word: 'play', phonetic: '/pleɪ/', meaning: '玩', example: 'Play games.' },
        { word: 'read', phonetic: '/riːd/', meaning: '读', example: 'Read a book.' },
        { word: 'write', phonetic: '/raɪt/', meaning: '写', example: 'Write your name.' },
        { word: 'run', phonetic: '/rʌn/', meaning: '跑', example: 'Run fast.' }
    ],
    2: [
        { word: 'friend', phonetic: '/frend/', meaning: '朋友', example: 'She is my best friend.' },
        { word: 'school', phonetic: '/skuːl/', meaning: '学校', example: 'I go to school every morning.' },
        { word: 'teacher', phonetic: '/ˈtiːtʃər/', meaning: '老师', example: 'My teacher is very kind.' },
        { word: 'student', phonetic: '/ˈstjuːdnt/', meaning: '学生', example: 'I am a student.' },
        { word: 'family', phonetic: '/ˈfæməli/', meaning: '家庭', example: 'I love my family.' },
        { word: 'home', phonetic: '/həʊm/', meaning: '家', example: 'Welcome to my home.' },
        { word: 'happy', phonetic: '/ˈhæpi/', meaning: '快乐的', example: 'I am very happy today.' },
        { word: 'beautiful', phonetic: '/ˈbjuːtɪfl/', meaning: '美丽的', example: 'What a beautiful day!' },
        { word: 'computer', phonetic: '/kəmˈpjuːtər/', meaning: '电脑', example: 'I use my computer every day.' },
        { word: 'book', phonetic: '/bʊk/', meaning: '书', example: 'This is a good book.' },
        { word: 'apple', phonetic: '/ˈæpl/', meaning: '苹果', example: 'I eat an apple every day.' },
        { word: 'water', phonetic: '/ˈwɔːtər/', meaning: '水', example: 'Drink more water.' },
        { word: 'food', phonetic: '/fuːd/', meaning: '食物', example: 'I like Chinese food.' },
        { word: 'time', phonetic: '/taɪm/', meaning: '时间', example: 'What time is it?' },
        { word: 'day', phonetic: '/deɪ/', meaning: '天', example: 'Have a nice day.' },
        { word: 'week', phonetic: '/wiːk/', meaning: '周', example: 'I go to school five days a week.' },
        { word: 'month', phonetic: '/mʌnθ/', meaning: '月', example: 'There are twelve months in a year.' },
        { word: 'year', phonetic: '/jɪər/', meaning: '年', example: 'Happy New Year!' },
        { word: 'good', phonetic: '/ɡʊd/', meaning: '好的', example: 'This is very good.' },
        { word: 'nice', phonetic: '/naɪs/', meaning: '美好的', example: 'You are a nice person.' }
    ],
    3: [
        { word: 'important', phonetic: '/ɪmˈpɔːtnt/', meaning: '重要的', example: 'This is very important.' },
        { word: 'different', phonetic: '/ˈdɪfrənt/', meaning: '不同的', example: 'We have different opinions.' },
        { word: 'practice', phonetic: '/ˈpræktɪs/', meaning: '练习', example: 'Practice makes perfect.' },
        { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: '改善', example: 'I want to improve my English.' },
        { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning: '挑战', example: 'This is a big challenge.' },
        { word: 'success', phonetic: '/səkˈses/', meaning: '成功', example: 'Success comes from hard work.' },
        { word: 'education', phonetic: '/ˌedʒuˈkeɪʃn/', meaning: '教育', example: 'Education is very important.' },
        { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: '交流', example: 'We need to communicate better.' },
        { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', meaning: '经验', example: 'She has rich experience.' },
        { word: 'opportunity', phonetic: '/ˌɒpəˈtjuːnəti/', meaning: '机会', example: 'This is a great opportunity.' },
        { word: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', meaning: '知识', example: 'Knowledge is power.' },
        { word: 'language', phonetic: '/ˈlæŋɡwɪdʒ/', meaning: '语言', example: 'English is a global language.' },
        { word: 'necessary', phonetic: '/ˈnesəsəri/', meaning: '必要的', example: 'It is necessary to study hard.' },
        { word: 'development', phonetic: '/dɪˈveləpmənt/', meaning: '发展', example: 'Economic development is important.' },
        { word: 'technology', phonetic: '/tekˈnɒlədʒi/', meaning: '技术', example: 'Technology changes our lives.' },
        { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: '环境', example: 'We should protect the environment.' },
        { word: 'society', phonetic: '/səˈsaɪəti/', meaning: '社会', example: 'We live in a modern society.' },
        { word: 'culture', phonetic: '/ˈkʌltʃər/', meaning: '文化', example: 'Different countries have different cultures.' },
        { word: 'journey', phonetic: '/ˈdʒɜːni/', meaning: '旅程', example: 'It was a long journey.' },
        { word: 'fantastic', phonetic: '/fænˈtæstɪk/', meaning: '极好的', example: 'That was a fantastic movie.' }
    ],
    4: [
        { word: 'perspective', phonetic: '/pəˈspektɪv/', meaning: '视角', example: 'Try to see things from a different perspective.' },
        { word: 'phenomenon', phonetic: '/fɪˈnɒmɪnən/', meaning: '现象', example: 'This is a natural phenomenon.' },
        { word: 'consequence', phonetic: '/ˈkɒnsɪkwəns/', meaning: '后果', example: 'Every action has its consequences.' },
        { word: 'fundamental', phonetic: '/ˌfʌndəˈmentl/', meaning: '基本的', example: 'This is a fundamental principle.' },
        { word: 'controversy', phonetic: '/ˈkɒntrəvɜːsi/', meaning: '争议', example: 'This issue caused much controversy.' },
        { word: 'comprehensive', phonetic: '/ˌkɒmprɪˈhensɪv/', meaning: '全面的', example: 'We need a comprehensive solution.' },
        { word: 'sophisticated', phonetic: '/səˈfɪstɪkeɪtɪd/', meaning: '复杂的', example: 'This is a sophisticated system.' },
        { word: 'inevitable', phonetic: '/ɪnˈevɪtəbl/', meaning: '不可避免的', example: 'Change is inevitable.' },
        { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', meaning: '完成', example: 'I accomplished my goal.' },
        { word: 'mysterious', phonetic: '/mɪˈstɪəriəs/', meaning: '神秘的', example: 'It was a mysterious event.' },
        { word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', meaning: '重要的', example: 'This is a significant achievement.' },
        { word: 'substantial', phonetic: '/səbˈstænʃl/', meaning: '大量的', example: 'There has been substantial progress.' },
        { word: 'considerable', phonetic: '/kənˈsɪdərəbl/', meaning: '相当大的', example: 'It requires considerable effort.' },
        { word: 'remarkable', phonetic: '/rɪˈmɑːkəbl/', meaning: '显著的', example: 'She made remarkable progress.' },
        { word: 'essential', phonetic: '/ɪˈsenʃl/', meaning: '必要的', example: 'Water is essential for life.' },
        { word: 'crucial', phonetic: '/ˈkruːʃl/', meaning: '关键的', example: 'This is a crucial decision.' },
        { word: 'vital', phonetic: '/ˈvaɪtl/', meaning: '至关重要的', example: 'Health is vital.' },
        { word: 'primary', phonetic: '/ˈpraɪməri/', meaning: '主要的', example: 'The primary goal is to succeed.' },
        { word: 'major', phonetic: '/ˈmeɪdʒər/', meaning: '主要的', example: 'This is a major issue.' },
        { word: 'dominant', phonetic: '/ˈdɒmɪnənt/', meaning: '主导的', example: 'English is the dominant language.' }
    ],
    5: [
        { word: 'ubiquitous', phonetic: '/juːˈbɪkwɪtəs/', meaning: '无处不在的', example: 'Smartphones are ubiquitous today.' },
        { word: 'paradigm', phonetic: '/ˈpærədaɪm/', meaning: '范式', example: 'This represents a new paradigm.' },
        { word: 'ephemeral', phonetic: '/ɪˈfemərəl/', meaning: '短暂的', example: 'Fame can be ephemeral.' },
        { word: 'pragmatic', phonetic: '/præɡˈmætɪk/', meaning: '务实的', example: 'We need a pragmatic approach.' },
        { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: '模糊的', example: 'The statement was ambiguous.' },
        { word: 'cohesive', phonetic: '/kəʊˈhiːsɪv/', meaning: '有凝聚力的', example: 'The team is very cohesive.' },
        { word: 'dichotomy', phonetic: '/daɪˈkɒtəmi/', meaning: '二分法', example: 'There is a dichotomy between theory and practice.' },
        { word: 'eloquent', phonetic: '/ˈeləkwənt/', meaning: '雄辩的', example: 'She gave an eloquent speech.' },
        { word: 'meticulous', phonetic: '/məˈtɪkjʊləs/', meaning: '一丝不苟的', example: 'He is meticulous about details.' },
        { word: 'pragmatism', phonetic: '/ˈpræɡmətɪzəm/', meaning: '实用主义', example: 'His approach is based on pragmatism.' },
        { word: 'resilience', phonetic: '/rɪˈzɪliəns/', meaning: '韧性', example: 'She showed great resilience.' },
        { word: 'scrutiny', phonetic: '/ˈskruːtəni/', meaning: '仔细审查', example: 'The project came under scrutiny.' },
        { word: 'tangible', phonetic: '/ˈtændʒəbl/', meaning: '有形的', example: 'We need tangible results.' },
        { word: 'ubiquity', phonetic: '/juːˈbɪkwɪti/', meaning: '无处不在', example: 'The ubiquity of technology is amazing.' },
        { word: 'verisimilitude', phonetic: '/ˌverɪsɪˈmɪlɪtjuːd/', meaning: '逼真', example: 'The movie has great verisimilitude.' },
        { word: 'axiomatic', phonetic: '/ˌæksiəˈmætɪk/', meaning: '公理的', example: 'It is axiomatic that practice improves skills.' },
        { word: 'cacophony', phonetic: '/kəˈkɒfəni/', meaning: '刺耳的声音', example: 'There was a cacophony of voices.' },
        { word: 'dogmatic', phonetic: '/dɒɡˈmætɪk/', meaning: '教条的', example: 'He has a dogmatic approach.' },
        { word: 'equivocal', phonetic: '/ɪˈkwɪvəkl/', meaning: '模棱两可的', example: 'His response was equivocal.' },
        { word: 'fastidious', phonetic: '/fæˈstɪdiəs/', meaning: '挑剔的', example: 'She is fastidious about cleanliness.' }
    ],
    6: [
        { word: 'acquiesce', phonetic: '/ˌækwiˈes/', meaning: '默许', example: 'He acquiesced to their demands.' },
        { word: 'bellicose', phonetic: '/ˈbelɪkəʊs/', meaning: '好战的', example: 'His bellicose attitude caused trouble.' },
        { word: 'cacophonous', phonetic: '/kəˈkɒfənəs/', meaning: '刺耳的', example: 'The cacophonous noise was unbearable.' },
        { word: 'deleterious', phonetic: '/ˌdelɪˈtɪəriəs/', meaning: '有害的', example: 'Smoking has deleterious effects.' },
        { word: 'ebullient', phonetic: '/ɪˈbʌliənt/', meaning: '热情洋溢的', example: 'She gave an ebullient speech.' },
        { word: 'fastidious', phonetic: '/fæˈstɪdiəs/', meaning: '挑剔的', example: 'He is fastidious about details.' },
        { word: 'garrulous', phonetic: '/ˈɡærjʊləs/', meaning: '唠叨的', example: 'She is a garrulous old woman.' },
        { word: 'hedonistic', phonetic: '/ˌhiːdəˈnɪstɪk/', meaning: '享乐主义的', example: 'His hedonistic lifestyle was criticized.' },
        { word: 'iconoclast', phonetic: '/aɪˈkɒnəklæst/', meaning: '打破旧习的人', example: 'He was an iconoclast in the art world.' },
        { word: 'juxtapose', phonetic: '/ˈdʒʌkstəpəʊz/', meaning: '并列', example: 'The artist juxtaposed contrasting colors.' },
        { word: 'kaleidoscope', phonetic: '/kəˈlaɪdəskəʊp/', meaning: '万花筒', example: 'Life is a kaleidoscope of experiences.' },
        { word: 'loquacious', phonetic: '/ləˈkweɪʃəs/', meaning: '话多的', example: 'She is a loquacious storyteller.' },
        { word: 'meticulous', phonetic: '/məˈtɪkjʊləs/', meaning: '一丝不苟的', example: 'He is meticulous about his work.' },
        { word: 'nonchalant', phonetic: '/ˈnɒnʃələnt/', meaning: '漠不关心的', example: 'She gave a nonchalant response.' },
        { word: 'obfuscate', phonetic: '/ˈɒbfʌskeɪt/', meaning: '使模糊', example: 'The lawyer tried to obfuscate the facts.' },
        { word: 'perspicacious', phonetic: '/ˌpɜːspɪˈkeɪʃəs/', meaning: '敏锐的', example: 'He is a perspicacious observer.' },
        { word: 'quintessential', phonetic: '/ˌkwɪntɪˈsenʃl/', meaning: '典型的', example: 'She is the quintessential professional.' },
        { word: 'recalcitrant', phonetic: '/rɪˈkælsɪtrənt/', meaning: '顽抗的', example: 'The recalcitrant student refused to cooperate.' },
        { word: 'serendipitous', phonetic: '/ˌserənˈdɪpɪtəs/', meaning: '偶然的', example: 'It was a serendipitous discovery.' },
        { word: 'ubiquitous', phonetic: '/juːˈbɪkwɪtəs/', meaning: '无处不在的', example: 'Technology is ubiquitous.' }
    ],
    7: [
        { word: 'antediluvian', phonetic: '/ˌæntɪdɪˈluːviən/', meaning: '古老的', example: 'His ideas are antediluvian.' },
        { word: 'calumny', phonetic: '/ˈkæləmi/', meaning: '诽谤', example: 'He sued for calumny.' },
        { word: 'dichotomy', phonetic: '/daɪˈkɒtəmi/', meaning: '二分法', example: 'There is a dichotomy between theory and practice.' },
        { word: 'ephemeral', phonetic: '/ɪˈfemərəl/', meaning: '短暂的', example: 'Fame is ephemeral.' },
        { word: 'flagitious', phonetic: '/fləˈdʒɪʃəs/', meaning: '罪恶的', example: 'He committed flagitious crimes.' },
        { word: 'gregarious', phonetic: '/ɡrɪˈɡeəriəs/', meaning: '爱交际的', example: 'She is a gregarious person.' },
        { word: 'harangue', phonetic: '/həˈræŋ/', meaning: '长篇大论', example: 'He gave a harangue about politics.' },
        { word: 'impecunious', phonetic: '/ˌɪmpɪˈkjuːniəs/', meaning: '贫穷的', example: 'He lived an impecunious life.' },
        { word: 'judicature', phonetic: '/ˈdʒuːdɪkətʃər/', meaning: '司法', example: 'The judicature system is fair.' },
        { word: 'kudos', phonetic: '/ˈkjuːdɒs/', meaning: '荣誉', example: 'He received kudos for his work.' },
        { word: 'loquacious', phonetic: '/ləˈkweɪʃəs/', meaning: '话多的', example: 'She is a loquacious speaker.' },
        { word: 'magnanimous', phonetic: '/mæɡˈnænɪməs/', meaning: '宽宏大量的', example: 'He showed magnanimous forgiveness.' },
        { word: 'nihilism', phonetic: '/ˈnaɪɪlɪzəm/', meaning: '虚无主义', example: 'His philosophy bordered on nihilism.' },
        { word: 'obstreperous', phonetic: '/əbˈstrepərəs/', meaning: '喧闹的', example: 'The obstreperous crowd caused chaos.' },
        { word: 'perspicacious', phonetic: '/ˌpɜːspɪˈkeɪʃəs/', meaning: '敏锐的', example: 'She made a perspicacious observation.' },
        { word: 'quintessence', phonetic: '/kwɪnˈtesns/', meaning: '精髓', example: 'This is the quintessence of beauty.' },
        { word: 'recondite', phonetic: '/ˈrekəndaɪt/', meaning: '深奥的', example: 'The theory is recondite.' },
        { word: 'sycophant', phonetic: '/ˈsaɪkəfænt/', meaning: '谄媚者', example: 'He is a sycophant to the boss.' },
        { word: 'ubiquitous', phonetic: '/juːˈbɪkwɪtəs/', meaning: '无处不在的', example: 'Social media is ubiquitous.' },
        { word: 'verisimilitude', phonetic: '/ˌverɪsɪˈmɪlɪtjuːd/', meaning: '逼真', example: 'The movie has great verisimilitude.' }
    ],
    8: [
        { word: 'abstruse', phonetic: '/əbˈstruːs/', meaning: '深奥的', example: 'The abstruse theory confounded everyone.' },
        { word: 'calumny', phonetic: '/ˈkæləmi/', meaning: '诽谤', example: 'He endured calumny from his enemies.' },
        { word: 'dichotomy', phonetic: '/daɪˈkɒtəmi/', meaning: '二分法', example: 'There is a dichotomy between theory and practice.' },
        { word: 'ephemeral', phonetic: '/ɪˈfemərəl/', meaning: '短暂的', example: 'Fame is ephemeral.' },
        { word: 'flagitious', phonetic: '/fləˈdʒɪʃəs/', meaning: '罪恶的', example: 'He committed flagitious crimes.' },
        { word: 'gregarious', phonetic: '/ɡrɪˈɡeəriəs/', meaning: '爱交际的', example: 'She is a gregarious person.' },
        { word: 'harangue', phonetic: '/həˈræŋ/', meaning: '长篇大论', example: 'He gave a harangue about politics.' },
        { word: 'impecunious', phonetic: '/ˌɪmpɪˈkjuːniəs/', meaning: '贫穷的', example: 'He lived an impecunious life.' },
        { word: 'judicature', phonetic: '/ˈdʒuːdɪkətʃər/', meaning: '司法', example: 'The judicature system is fair.' },
        { word: 'kudos', phonetic: '/ˈkjuːdɒs/', meaning: '荣誉', example: 'He received kudos for his work.' },
        { word: 'loquacious', phonetic: '/ləˈkweɪʃəs/', meaning: '话多的', example: 'She is a loquacious speaker.' },
        { word: 'magnanimous', phonetic: '/mæɡˈnænɪməs/', meaning: '宽宏大量的', example: 'He showed magnanimous forgiveness.' },
        { word: 'nihilism', phonetic: '/ˈnaɪɪlɪzəm/', meaning: '虚无主义', example: 'His philosophy bordered on nihilism.' },
        { word: 'obstreperous', phonetic: '/əbˈstrepərəs/', meaning: '喧闹的', example: 'The obstreperous crowd caused chaos.' },
        { word: 'perspicacious', phonetic: '/ˌpɜːspɪˈkeɪʃəs/', meaning: '敏锐的', example: 'She made a perspicacious observation.' },
        { word: 'quintessence', phonetic: '/kwɪnˈtesns/', meaning: '精髓', example: 'This is the quintessence of beauty.' },
        { word: 'recondite', phonetic: '/ˈrekəndaɪt/', meaning: '深奥的', example: 'The theory is recondite.' },
        { word: 'sycophant', phonetic: '/ˈsaɪkəfænt/', meaning: '谄媚者', example: 'He is a sycophant to the boss.' },
        { word: 'ubiquitous', phonetic: '/juːˈbɪkwɪtəs/', meaning: '无处不在的', example: 'Social media is ubiquitous.' },
        { word: 'verisimilitude', phonetic: '/ˌverɪsɪˈmɪlɪtjuːd/', meaning: '逼真', example: 'The movie has great verisimilitude.' }
    ]
};

function getAllVocabulary(level) {
    return VOCABULARY_BY_LEVEL[level] || [];
}

function getLevelInfo(level) {
    return VOCABULARY_LEVELS[level] || VOCABULARY_LEVELS[1];
}
